[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
encrypted_poker = "AxwPZ5ZiuZwrFss1jjFh5zAozYt2EKBZYT9Mw2wN7fye"

[programs.localnet]
encrypted_poker = "AxwPZ5ZiuZwrFss1jjFh5zAozYt2EKBZYT9Mw2wN7fye"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
bind_address = "127.0.0.1"
startup_wait = 100000
warp_slot = 200
